// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/editor.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Author.tsx";
import * as $$1 from "./islands/Background.tsx";
import * as $$2 from "./islands/Confettis.tsx";
import * as $$3 from "./islands/Editor.tsx";
import * as $$4 from "./islands/Footer.tsx";
import * as $$5 from "./islands/Header.tsx";
import * as $$6 from "./islands/Home.tsx";
import * as $$7 from "./islands/Usage.tsx";
import * as $$8 from "./islands/confettis/Advanced.tsx";
import * as $$9 from "./islands/confettis/Cookies.tsx";
import * as $$10 from "./islands/confettis/Default.tsx";
import * as $$11 from "./islands/confettis/Drop.tsx";
import * as $$12 from "./islands/confettis/Emojis.tsx";
import * as $$13 from "./islands/confettis/Fireworks.tsx";
import * as $$14 from "./islands/confettis/Hearts.tsx";
import * as $$15 from "./islands/confettis/Party.tsx";
import * as $$16 from "./islands/confettis/Random.tsx";
import * as $$17 from "./islands/confettis/Snow.tsx";
import * as $$18 from "./islands/confettis/Stars.tsx";
import * as $$19 from "./islands/confettis/Test.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/editor.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Author.tsx": $$0,
    "./islands/Background.tsx": $$1,
    "./islands/Confettis.tsx": $$2,
    "./islands/Editor.tsx": $$3,
    "./islands/Footer.tsx": $$4,
    "./islands/Header.tsx": $$5,
    "./islands/Home.tsx": $$6,
    "./islands/Usage.tsx": $$7,
    "./islands/confettis/Advanced.tsx": $$8,
    "./islands/confettis/Cookies.tsx": $$9,
    "./islands/confettis/Default.tsx": $$10,
    "./islands/confettis/Drop.tsx": $$11,
    "./islands/confettis/Emojis.tsx": $$12,
    "./islands/confettis/Fireworks.tsx": $$13,
    "./islands/confettis/Hearts.tsx": $$14,
    "./islands/confettis/Party.tsx": $$15,
    "./islands/confettis/Random.tsx": $$16,
    "./islands/confettis/Snow.tsx": $$17,
    "./islands/confettis/Stars.tsx": $$18,
    "./islands/confettis/Test.tsx": $$19,
  },
  baseUrl: import.meta.url,
};

export default manifest;
